Post/Post/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static ,re_path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("app.urls")),
    path("api/",include("blog_api.urls")),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [re_path(r'^.*',TemplateView.as_view(template_name='index.html'))]    

Post/app/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import ( Home, Create, Update, Delete, Index, LoginPage, PostView, 
                     RegisterPage, LogoutView, comment_delete,like,aboutPage,Footer)
from django.contrib.auth import views as auth_views
from marketing.views import email_list_signup

urlpatterns = [

    path("", Index, name="home"),
    path("blog/", Home, name="blog"),
    path("postview/<slug>", PostView, name="postview"),
    path("create/", Create, name="create"),
    path("update/<slug>", Update, name="update"),
    path("delete/<slug>", Delete, name="delete"),
    path('login/', LoginPage, name="login"),
    path('register/', RegisterPage, name="register"),
    path('logout/', LogoutView, name="logout"),
    path('comment_delete/<id>', comment_delete, name='comment_delete'),
    path('like/', like, name="like"),
    path('about/', aboutPage, name= "about"),
    path('subscribe/', email_list_signup, name="subscribe"),
    path('footer/', Footer, name="footer"),

  

]

Post/marketing/models.py
from django.db import models
from app.models import CreatePost
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from mptt.models import MPTTModel,TreeForeignKey
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
import re
from django.conf import settings

class Comment(MPTTModel): 
    user            =     models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    post            =     models.ForeignKey(CreatePost,on_delete=models.CASCADE,blank=True,null=True,related_name="comments")
    parent          =     TreeForeignKey('self',on_delete=models.CASCADE,blank=True,null=True,related_name="children")
    slug            =     models.SlugField()
    email           =     models.EmailField()
    content         =     models.TextField()
    publish_date    =     models.DateTimeField(auto_now_add=True)
    status          =     models.BooleanField(default=True)

    class MPTTMeta: 
        order_insertion_by = ['publish_date']
 
    def __str__(self): 
        return f'comment by {self.user} in {self.post}' 

 

    def get_absoulte_url(self):
        return reverse("postview",kwargs={"slug":self.slug})    


class SubscribeModel(models.Model):
    email = models.EmailField(null=False, blank=True, max_length=200, unique=True)
    created_date = models.DateTimeField(null=False, blank=True,auto_now_add=True)

    def __str__(self):
        return self.email


def create_comment_slug(instance,new_slug=None):
    slug = slugify(instance.post)
    if new_slug is not None:
        slug = new_slug
    qs = Comment.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug,qs.first().id)
        return create_comment_slug(instance,new_slug=new_slug)
    res = re.findall(r'\w+', slug)
    return res[0]

def pre_save_post_receive(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = create_comment_slug(instance)
    

pre_save.connect(pre_save_post_receive,sender=Comment) 


Post/app/templates/Navbar.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="http://code.jquery.com/jquery-3.5.1.js"></script>
    <style>
        nav ul li {
            color: #1a1517;
            background: transparent;
        }

        nav ul li .active {
            color: #ffffff;
            border-radius: 5px;
            font-weight: 800;
            background: linear-gradient(#e66465, #9198e5);
            transition: 0.5s;
        }

        nav ul li a:hover {
            color: #ffffff;
            font-weight: 900;
            background: linear-gradient(#e66465, #9198e5);
            transition: 0.5s;
        }

        .myNav {
            background-image: linear-gradient(#e7e2dcb9, #d1ccc6be);
        }
    </style>
</head>

<body>
    <nav class="myNav">
        <input type="checkbox" id="check" />
        <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
        </label>
        <div class="logo">
            <a href="{% url 'home' %}" style="background: transparent;"> Ind<span>sey</span><em>love</em></a>
        </div>
        <ul>
            <li><a href="{% url 'home'  %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'blog'  %}">Blog</a></li>
            {% if request.user.is_superuser %}
            <li><a href="{% url 'create'  %}"> Create Blog </a></li>
            {% endif %}
            <li><a href="{% url 'register'  %}">SignUp</a></li>
            {% if request.user.is_superuser or request.user.is_active %}
            <li><a href="{% url 'logout'  %}">Logout</a></li>
            {% endif %}
        </ul>

        <section></section>
    </nav>
    <script src="http://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript">
        const currentLocation = location.href;
        const menuItem = document.querySelectorAll('a');
        console.log(menuItem)
        const menuItemLength = menuItem.length;
        for (let i = 0; i < menuItemLength; i++) {
            if (menuItem[i].href === currentLocation) {
                menuItem[i].className = "active";

            }
            
        }
    </script>
</body>

</html>

Post/app/templates/Password_reset_done.html
<!DOCTYPE html>
<html>

<head>
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4>Well done!</h4>
        <p>An Email has been sent with instructions to reset your password. <b>Check Your Email!</b></p>
        <hr>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>

</html>

Post/app/templates/about.html
{% extends 'base.html' %}
{% block content %}
{% include 'Navbar.html' %}

<div class="page-heading">
    <div class="container">
        <div class="heading-content">
            <h1 style="color: aliceblue;">About Page</h1>
        </div>
    </div>
</div>
<div class="blog-entries">
    <div class="container">
        <div class="col-md-8">
            <div class="blog-posts">
                <div class="row">
                    <div class="col-md-12">
                        <div class="blog-post">
                            <h4>Kamal Kishor Pandey</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

Post/app/templates/blog.html
{% extends 'base.html' %}
{% block content %}
{% include 'Navbar.html' %}

<div class="page-heading">
  <div class="container">
    <div class="heading-content">
      <h1>Our <em>Blog</em></h1>
    </div>
  </div>
</div>


<div class="blog-entries">
  <div class="container">
    <div class="col-md-8">
      <div class="blog-posts">
        <div class="row">
          {% for data in post %}
          <div class="col-md-12">
            <div class="blog-post">
              <img src="{{data.image.url}}" alt="">
              <div class="text-content text-info">
                <span><small><a href="#"><i class="fa fa-user" aria-hidden="true"></i> {{data.author}}</a> &nbsp; <a
                      href="#"><i class="fa fa-clock-o" aria-hidden="true"></i> {{data.publish_date|timesince}} ago</a>
                    &nbsp; <a href="#"><i class="fa fa-comment" aria-hidden="true"></i> {{ data.get_comments.count }}
                      Comment{{ data.get_comments.count|pluralize }}</a>
                    &nbsp; <a href="#"><i class="fa fa-heart" aria-hidden="true"></i> {{ data.number_of_likes }} Like{{data.number_of_likes |pluralize }}</a>
                  </small>
                </span>
                <h2>{{data.title}}</h2>
                <p>{{data.content|safe|truncatewords:60}}</p>

                {% if request.user.is_active or request.user.is_superuser %}
                <div class="simple-btn">
                  <a href="{% url 'postview' data.slug %}">continue reading</a>
                </div>
                {% else %}
                <div class="simple-btn">
                  <p class="text-info">To Read More You must <a href="{% url 'login'  %}"> login first</a></p>
                </div>
                {% endif %}
              </div>
            </div>

          </div>
          {% endfor %}


          <div class="col-md-12 mb-5">
            <div aria-label="Pagdivigation example">

              <ol class="justify-content-center text-center text-capitalize mb-5 font-weight-bolder pagination">
                {% if post.has_previous %}
                <li class="page-item d-inline p-0"> <a style="color: #232323;"
                    href="?{{page_request_var}}=1 {% if request.GET.q %}&q={{request.GET.q}}{% endif %}  ">&laquo;
                    first</a></li>
                <li class="page-item d-inline p-0"><a style="color: #232323; "
                    href="?{{page_request_var}}={{ post.previous_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">previous</a>
                </li>
                {% endif %}

                <li class="active page-item d-inline p-0 text-danger bg-transparent">
                  <a>Page ( {{ post.number }} of {{ post.paginator.num_pages }} )</a>
                </li>

                {% if post.has_next %}
                <li class="page-item d-inline p-0"><a style="color: #232323; "
                    href="?{{page_request_var}}={{ post.next_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">next</a>
                </li>
                <li class="page-item d-inline p-0"><a style="color: #232323; "
                    href="?{{page_request_var}}={{ post.paginator.num_pages }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">last
                    &raquo;</a></li>
                {% endif %}
              </ol>
            </div>

          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="side-bar">
        {% include 'sidebar.html' %}
      </div>
    </div>

  </div>
</div>
<script>
  $(document).on('click', '#like-button', function (e) {
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "like" %}',
      data: {
        postid: $('#like-button').val(),
        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
        action: 'post'
      },
      success: function (json) {
        document.getElementById("like_count").innerHTML = json['result']
      },
      error: function (xhr, errmsg, err) {

      }
    });
  });

</script>

{% endblock %}

Post/app/templates/comment_delete.html
{% extends 'base.html' %}

{%block content %}
{% include 'Navbar.html' %}
<div class="page-heading">
    <div class="container">
        <div class="heading-content">
            <h1>Delete <em>Comment</em></h1>
        </div>
    </div>
</div>

<div class="blog-entries">
    <div class="container" style="color: wheat;">
        <form method="POST" action="">{% csrf_token %}
            <span>
                <h5>Are you sure to Delete "{{object.content}}" ?</h5>
            </span><br>
            <input type="submit" value="Confirm" class="btn btn-warning" />
            <a href="{{object.get_absoulte_url}}" class="btn btn-danger">Cancel</a>
        </form>
    </div>
</div>


{% endblock %}

Post/app/templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'Navbar.html' %}
<div class="page-heading">
    <div class="container">
        <div class="heading-content">
            <h1>Create <em>Posts</em></h1>
        </div>
    </div>
</div>

<div class="blog-entries">
    <div class="container" style="color: wheat;">
        <div class="card mb-5">
        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
            {{forms.media}}
            {{forms|crispy}}
            <input type="submit" class="btn btn-primary" value="Create" />
        </form>
    </div>
    </div>
</div>

{% endblock %}

Post/app/templates/delete.html
<h1>{{title}}</h1>
<form  method="POST" action="">{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Delete" />
</form>

Post/app/templates/footer.html
<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4 ">
                    <h3>Subscribe Newsletter </h3>
                    <p>Get all the latest information on Triedge Services, Events, Jobs
                        and Fairs. Sign up for our newsletter today.</p>
                </div>
                <div class="col-md-4 col-sm-12 mb-5">
                    <form class="newsletter" action="{% url 'subscribe' %}" method="POST">{% csrf_token %}
                        {{Subscribeform}}
                        <button class="newsletter_submit_btn" type="submit"><i class="fa fa-paper-plane"></i></button>
                        
                    </form>
                </div>
                <div class="col-md-4 col-sm-12 col item social">
                    <div class="col-md-12 col-sm-12">
                        <div class="standard_social_links ml-5 ">
                            <div class="text-center align-items-sm-center">
                                <li class="round-btn btn-facebook"><a target="_blank"
                                        href="https://www.facebook.com/kamal.pandey.12"><i
                                            class="fab fa-facebook-f"></i></a>
                                </li>
                                <li class="round-btn btn-linkedin"><a target="_blank"
                                        href="https://www.linkedin.com/in/kamal-kishor-50685760/"><i
                                            class="fab fa-linkedin-in" aria-hidden="true"></i></a>
                                </li>
                                <li class="round-btn btn-twitter"><a target="_blank" href="#"><i class="fab fa-twitter"
                                            aria-hidden="true"></i></a>
                                </li>
                                <li class="round-btn btn-instagram"><a target="_blank"
                                        href="https://www.instagram.com/indseylove/"><i class="fab fa-instagram"
                                            aria-hidden="true"></i></a>
                                </li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <p class="copyright col-sm-12 text-center">Indeseylove © 2020-
                    <script>document.write(new Date().getFullYear());</script>
                </p>
            </div>
    </footer>
</div>

Post/app/templates/index.html
{% extends 'base.html' %}


{% block content %}

{% include 'Navbar.html' %} 


<div id="video-container">

  <div class="video-content">
    
    <div class="inner">
      <h1  style="text-shadow: 1px -1px 0 #035c0b;">Welcome to <em>Ind<em class="say">sey</em><em class="love">Love</em></em></h1>
      <p style="font-weight: 500; font-size: 30px;  text-shadow: 1px -1px 0 #42afac;">The journey of a thousand miles begins with a single step</p>

      
    </div>
  </div>

  <img src="../static/img/Mountain.jpg" />

</div>


<div class="full-screen-portfolio" id="portfolio">
  <div class="container-fluid">
    {% for img in images %}
    <div class="col-md-4 col-sm-6">
      <div class="portfolio-item">
        <a href="{{img.image.url}}" data-lightbox="image-1" alt="image">
          <div class="thumb">
            <div class="hover-effect">
              <div class="hover-content ">
                <h1>{{img.title}}</h1>
              </div>
            </div>
            <div class="image">
              <img src="{{img.image.url}}" width="100%" height="300px" />
            </div>
          </div>
        </a>
      </div>
    </div>
    {% endfor %}

  </div>
</div>
</section>


{% endblock %}

Post/app/templates/password_reset.html

<!DOCTYPE html>
<html>

<head>
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
    {% load crispy_forms_tags %}
    <div class="container align-items-center bg-info">
        <div class="card " style="margin-top:120px ;" > 
            <h2 class="card-header">Account recovery</h2>
            <div class="card-body">
                <form method="POST"> {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-block btn-primary mt-3">Reset Password</button>
                </form>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>

</html>

Post/app/templates/password_reset_complete.html
<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
</head>
<body>
    <h1>Password Reset Complete</h1> <a href="{% url 'login' %}">Login</a>
</body>
</html>

Post/app/templates/password_reset_confirm.html
<!DOCTYPE html>
<html>

<head>
    <title>{{title}}</title>
</head>

<body>
    <h1>Reset Your Password</h1>
    <h5>Enter Your New Password</h5>
    <form method="POST"> {% csrf_token %}
        {{form}}
        <button type="submit">Change Password</button>
    </form>
</body>

</html>

Post/app/templates/single-post.html
{% extends 'base.html' %}

{% block content %}
{% include 'Navbar.html' %}
<style>
  @import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=PT+Serif:wght@400;700&display=swap');

  .h1 {
    font-family: 'PT Serif', serif;
    font-size: 2.55rem;
    line-height: 2.6rem;
    letter-spacing: -0.063px;
  }

  h2 {
    font-family: 'PT Serif', serif;
    font-size: 1.9rem;
    line-height: 2.6rem;
    letter-spacing: -0.063px;
    font-weight: 700;
    padding-top: 48px;
  }

  p {
    font-family: 'PT Serif', serif;
    line-height: 2rem;
    font-size: 1.3rem
  }
</style>
<div class="page-heading">
  <div class="container">
    <div class="heading-content">
      <h1 style=" background: linear-gradient(#e66465, #9198e5); border-radius: 10px;">{{post.title}}</h1>
    </div>
  </div>
</div>


<div class="blog-entries">
  <div class="container">
    <div class="col-md-8">
      <div class="blog-posts">
        <div class="row">
          <div class="col-md-12">
            <div class="single-blog-post">
              <img src="{{post.image.url}}" alt="post-image">
              <div class="text-content">
                <h2>{{post.title}}</h2>
                <span class="d-inline-block d-flex"><small class="mt-1"><a href="#" class="text-info"><i class="fa fa-user" aria-hidden="true"></i> {{post.author}}</a></small>
                  &nbsp;&nbsp; <a href="" class="text-info"><i class="fa fa-clock-o" aria-hidden="true"></i>
                    <small>{{post.publish_date|timesince}} ago</small> </a>
                  &nbsp;&nbsp; <a href="" class="text-info"><i class="fa fa-comment" aria-hidden="true"></i> <small>{{ post.get_comments.count }} Comment{{post.get_comments.count| pluralize}}</small>   </a>
                  &nbsp;&nbsp;
                  {% if request.user.is_authenticated %}
                  <small class="mt-1">
                    <button class="btn btn-link text-dark p-0 border-0 btn-outline-light btn-sm"  id="like-button" value="{{post.id}}">
                      <small><i class="fa fa-heart fa-2x text-info" aria-hidden="true"></i></small>
                    </button>
                    <a class="text-info" id="like_count"> {{ post.number_of_likes  }} </a > <a class="text-info">   Like{{ post.number_of_likes |pluralize }}</a>
                  </small>
                    {% endif %}  
                </span>
                <p>{{post.content|safe}}
                  <br><br><a href="{% url 'blog' %}">Back to Blog</a>
                </p>
                <div class="tags-share">
                  <div class="row">
                    <div class="col-md-6">
                  
                    </div>
                    <div class="col-md-6">
                      <ol class="share">
                        <li>Share:</li>
                        <li><a href="#">facebook</a>,</li>
                        <li><a href="#">twitter</a>,</li>
                        <li><a href="#">behance</a></li>
                      </ol>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% load mptt_tags %}
      <div>
        <h1 class="bg-primary mb-3 card card-header">Comments({{post.get_comments.count}})</h1>
        {% if post.get_comments.count >= 20 %} <div style="overflow-y:scroll; height:500px"> {% else %} <div> {% endif %}
            
            {% recursetree post.get_comments %}
            <div class="card" style="background:transparent; color: #f1f1f1;">

              {% if not request.user.is_active or not request.user.is_superuser %}
              <h4><i class="fa fa-user-circle fa-2x mt-1" aria-hidden="true"></i> <span
                  class="card-title">{{node.user}}</span> <small class="date">{{node.publish_date|timesince}}
                  ago</small>
              </h4>

              {% else %}
              <h4><i class="fa fa-user-circle fa-2x mt-1" aria-hidden="true"></i> <span
                  class="card-title">{{node.user}}</span> <small class="date">{{node.publish_date|timesince}}
                  ago</small>
              </h4>
              {% endif %}

              <div id={{node.id}}>{{node.content}}</div>
              <div class="d-flex justify-content-between">
                {% if not node.is_leaf_node %}<div>
                  <div class="border-0 bg-transparent m-3" style="cursor: pointer;"><a class="active bg-transparent"
                      onclick="myReplyFunction(`{{node.id}}+1`)" id={{node.id}}+11>View_Replies</a href="#"></div>
                </div>{% else %} <div></div> {% endif %}
                <div>
                  {% if not node.user|stringformat:"s" == request.user.username %}
                  <button class="btn btn-outline-primary text-center m-3"
                    style="color: #f1f7f8; width: 100%;border: none;" onclick="myFunction('{{node.id}}')">Reply</button>
                  {% endif %}
                  {% if node.user|stringformat:"s" == request.user.username %}
                  <button class="btn btn-outline-primary  m-3"  style="color: #f1f7f8; width: 100%;border: none;"><a
                      href="{% url 'comment_delete' node.id  %}">Delete</a></button>
                  {% endif %}
                 


                </div>
              </div>
            </div>

            {% if not node.is_leaf_node %}
            <div id={{node.id}}+1 style="display: none;">
              <div class="children pl-5 pl-md-5 ">
                {{ children }}
              </div>
            </div>
            {% endif %}

            {% endrecursetree %}
          </div>
        </div>
        <hr />
        <div style="color: wheat; font-size: 12px;">
          <label class="text-info required" class=" requiredField">Leave Your message</label>
          {% load crispy_forms_tags %}
          <form method="POST">{% csrf_token %}
            {{forms|crispy}}
            <button class="btn btn-primary  btn-lg mb-5 mb-sm-5" type="submit">Share</button>
          </form>
        </div>
      </div>
      <div class="col-md-4">
        <div class="side-bar">
          {% include 'sidebar.html' %}
        </div>
      </div>
    </div>
  </div>




  
  <script>

    function myReplyFunction(id) {

      var x = document.getElementById(id);

      if (x.style.display === "none") {
        document.getElementById(id + 1).innerHTML = "Hide_Replies";
        document.getElementById(id + 1).style.color = "#066ee4";
        x.style.display = "block";
      } else {
        document.getElementById(id + 1).innerHTML = "View_Replies";
        document.getElementById(id + 1).style.color = "#066ee4";
        x.style.display = "none";
      }

    }
    function formExit() {
      document.getElementById("commentForm").remove();
    }

    function myFunction(id) {
      if (document.contains(document.getElementById("commentForm"))) {
        document.getElementById("commentForm").remove();
      }

      var g = document.getElementById(id);
      g.insertAdjacentHTML('afterend',
        '<form method="POST" id="commentForm" style="color: wheat; font-size: 12px;">\
            <div class="d-flex justify-content-between">\
            <h3 class="text-info">Reply</h3>\
            <div><button type="button" class="btn btn-outline-primary" onclick=formExit()><i class="fa fa-times-circle" aria-hidden="true"></i></button></div>\
            </div> \
            </div> </div> <div id="div_id_parent" class="form-group">  <div class=""> \
            <select name="parent" class="d-none select form-control" id="id_parent"><option value=" ' + id + ' " selected=" ' + id + '"></option></select>\
            </div> </div>\
            <div id="div_id_content" class="form-group"> <label for="id_content" class=" requiredField">Content<span class="asteriskField">*</span> </label> \
            <div class=""> <textarea name="content" cols="40" rows="1" style="color: white; font-size: 16px; font-weight:200;" class="border-top-0 border-left-0 border-right-0 border-bottom-40  border-info bg-transparent form-control mt-2 textarea form-control" placeholder="Write your reply..." required="" id="id_content">\
            </textarea> </div> </div>\
            {% csrf_token %}\
            <button class="btn btn-primary full-screen-portfolio">Reply</button>\
        </form>'
      );

    }
    $('#commentForm').trigger('reset');

    $(document).on('click', '#like-button', function (e) {
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "like" %}',
      data: {
        postid: $('#like-button').val(),
        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
        action: 'post'
      },
      success: function (json) {
        document.getElementById("like_count").innerHTML = json['result']
      },
      error: function (xhr, errmsg, err) {

      }
    });
  });

  </script>



  {% endblock %}